### ISSUE TITLE
Image URL Validation

### ISSUE THREAD

**Issue by AppFolioRopes** [AppFolioOnboarding/Jeremy#4]
#### As a user I want to be prevented from submitting invalid image URLs.

Acceptance criteria:
- [x] I cannot successfully save an image with an invalid URL.
- [x] An error message is associated with the appropriate input field on
  failure.

Discussion Topic:
- [ ] What is a valid image URL?

Dependencies:
- Save Image Link

**Comment by jeremyjpark** [comment]
Is a valid image URL a url that is only an image? ie, ends with some sort of image file extension, or is it supposed to be a valid url with an image somewhere in the page?
